### PR TITLE
New API for v0.6

### PR DESCRIPTION
**Pull request by my8bird**

### CODE REVIEW

**Comment by creationix** [comment]
Wow, how am I supposed to review 11 months of commits at once?!  This is more than just fixing for v0.4.x-v0.6.x api changes.

**Comment by creationix** [comment]
I am impressed with the amount of work that has been going on with this in the various forks.  Hopefully I can get all this merged upstream.

**Comment by my8bird** [comment]
I made a much cleaner one if you want to use that instead.  I used
rebase so that the merge would be much cleaner.

mike kind of sprung this massive list of commits on me and I thought
you might like them also see as it all is based on your start.

On Feb 20, 2012, at 4:56 PM, Tim Caswell
reply@reply.github.com
wrote:

**Comment by pvorb** [comment]
truly epic

**Pull request closed without merging**
