### PR TITLE
Fixed build for Node.js 0.5/0.6

### PR DESCRIPTION
**Pull request by justmoon**
Did the basic build changes required to get this module running under the new Node.js 0.6 stable. Tested the build under both 0.4.12 and 0.6.

### CODE REVIEW

**Comment by justmoon** [comment]
Poke! There's [plenty more](https://github.com/justmoon/node-leveldb/commits/fix_n_update) where this came from. ;)

**Comment by justmoon** [comment]
Bump again.

**Comment by booo** [comment]
Could you please add this!

**Comment by justmoon** [comment]
This patch landed in https://github.com/my8bird/node-leveldb along with a large number of other fixes and improvements.

my8bird's repository is also what you get if you run `npm install leveldb`.

**Comment by justmoon** [comment]
See: https://github.com/my8bird/node-leveldb/pull/1

**Comment by booo** [comment]
Thx! Looks pretty good.

@creationix do you still maintain the code base here? If not could you delete this repo or add a short notice about the fact that you do not? This repo is the first hit at google and confused at least me a bit.

**Pull request closed without merging**
