### PR TITLE
Add a memcached adapter 

### PR DESCRIPTION
**Pull request by killme2008**
hi,all
Thanks for your great job.

I have added a memcached adapter for node-levelDB to allow any people using it with memcached text protocol.
You can type

node memcached-adapter/memcached.js

to start the adapter server and telnet localhost 11211 to test it.Now it only supports set/get/delete protocols.

If you feel it is useful,please merge it to master.

### CODE REVIEW

**Comment by tilgovi** [comment]
First off: very cool! I think many people would find this interesting.
On the other hand, my gut says this is a separate project. I'd like to resist the temptation to let node-leveldb creep beyond a simple API wrap over leveldb. Keeping the scope of _this_ project very limited means it'll be easy to maintain and test.

Does this make sense or am I being a curmudgeon?

**Comment by killme2008** [comment]
You are right,it's better to keep node-leveldb clean and simple.It's a great job,thanks for your reply.

**Comment by tilgovi** [comment]
Definitely post this code somewhere, though!

**Comment by creationix** [comment]
When you post the code somewhere, please link to it in the wiki for this project. You can make a new page called "projects using node-leveldb" or something.

**Pull request closed without merging**
